import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
// import "./globals.css";
import NombreRol from "../components/nombrerol/nombrerol";

const ubuntu = Ubuntu({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Merlo, Santiago - CV ",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
            <body className={`${ubuntu.className} antialiased`}>
                <NombreRol></NombreRol>
                <div className="mx-auto px-40">{children}</div>
            </body>
        </html>
    );
}
